export { analyzeSite } from "./analyzer.js";
export { analyzeLogs } from "./logs/index.js";
export { scanDirectory } from "./directory-scanner.js";
export type { DirectoryScanOptions } from "./directory-scanner.js";
export {
  buildKeywordSummary,
  countOccurrences,
  extractTermFrequencies,
  matchKeywordsOnPage,
} from "./keywords.js";
export type { PageTextContent } from "./keywords.js";
export type {
  AnalyzeLogsOptions,
  AnalyzeOptions,
  AnalyzeProgressEvent,
  AnalyzeProgressPhase,
  AnalyzeProgressStage,
  ContentCluster,
  ContentClusterMember,
  ContentDedupReport,
  DnsResolver,
  DuplicateGroup,
  ExtractionResult,
  ExtractionRule,
  ExtractionSummary,
  InfrastructureReport,
  Issue,
  KeywordLocationCounts,
  KeywordMatch,
  KeywordSummary,
  LighthouseMetrics,
  LighthouseReport,
  LighthouseScores,
  LinkGraphPage,
  LinkGraphReport,
  LinkGraphTopEntry,
  LogAnalysisBaseline,
  LogAnalysisProgressEvent,
  LogAnalysisReport,
  LogTimeWindow,
  OrphanFinding,
  PageChecks,
  PageReport,
  Severity,
  SiteReport,
  SiteSummary,
  StaleFinding,
  StatusMismatchFinding,
  TermFrequency,
  VerifiedBot,
} from "./types.js";
